/* Generated by Curium v5 compiler — do not edit */
#include "curium/core.h"
#include "curium/memory.h"
#include "curium/string.h"
#include "curium/list.h"
#include "curium/array.h"
#include "curium/map.h"
#include "curium/safe_ptr.h"
#include "curium/option.h"
#include "curium/result.h"
#include "curium/http.h"
#include "curium/thread.h"
#include "curium/file.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <setjmp.h>
#include <stdint.h>

/* Exception Handling Runtime */
#define CURIUM_MAX_EX_DEPTH 64
/* FIX #014: exception globals are _Thread_local so that spawn {} threads
 * have independent exception stacks — a throw on one thread no longer
 * corrupts another thread's setjmp/longjmp state.                      */
#if defined(__TINYC__)
#  define CURIUM_TLS  /* TCC: no TLS support */
#elif defined(_MSC_VER)
#  define CURIUM_TLS __declspec(thread)
#elif defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L
#  define CURIUM_TLS _Thread_local
#elif defined(__GNUC__) || defined(__clang__)
#  define CURIUM_TLS __thread
#else
#  define CURIUM_TLS  /* no TLS support — fallback to global */
#endif
CURIUM_TLS jmp_buf _curium_ex_stack[CURIUM_MAX_EX_DEPTH];
CURIUM_TLS int _curium_ex_depth = 0;
CURIUM_TLS void* _curium_current_exception = NULL;

#define CURIUM_THROW_IMPL(ex) do { \
    _curium_current_exception = (void*)(ex); \
    if (_curium_ex_depth > 0) longjmp(_curium_ex_stack[_curium_ex_depth - 1], 1); \
    else { fprintf(stderr, "Uncaught exception\n"); exit(1); } \
} while(0)

static inline void* curium_result_unwrap_or_throw(curium_result_t res) {
    if (res.kind == CURIUM_RESULT_ERR) CURIUM_THROW_IMPL(curium_string_new("Result Error"));
    return res.value;
}

#define CURIUM_RESULT_OK(val)  curium_result_ok( &(val),  sizeof(val) )
#define CURIUM_RESULT_ERR(err) curium_result_err(&(err),  sizeof(err) )
#define CURIUM_OPTION_SOME(val) curium_option_some(&(val), sizeof(val))
#define CURIUM_OPTION_NONE CURIUM_OPTION_NONE_INIT

/* Type Erasure for Generics (Fallback to void*) */
typedef void* T;
typedef void* U;
typedef void* K;
typedef void* V;

#define curium_any_to_str(v) _Generic((v),                                   \
    curium_string_t*: ((curium_string_t*)(v))->data,                          \
    char*:            (v),                                                    \
    const char*:      (v),                                                    \
    int:              (snprintf(_curium_fmt_buf, sizeof(_curium_fmt_buf), "%d", (int)(v)),      _curium_fmt_buf), \
    unsigned int:     (snprintf(_curium_fmt_buf, sizeof(_curium_fmt_buf), "%u", (unsigned int)(v)), _curium_fmt_buf), \
    long:             (snprintf(_curium_fmt_buf, sizeof(_curium_fmt_buf), "%ld", (long)(v)),    _curium_fmt_buf), \
    unsigned long:    (snprintf(_curium_fmt_buf, sizeof(_curium_fmt_buf), "%lu", (unsigned long)(v)), _curium_fmt_buf), \
    double:           (snprintf(_curium_fmt_buf, sizeof(_curium_fmt_buf), "%g",  (double)(v)),   _curium_fmt_buf), \
    float:            (snprintf(_curium_fmt_buf, sizeof(_curium_fmt_buf), "%g",  (double)(v)),   _curium_fmt_buf), \
    default:          (snprintf(_curium_fmt_buf, sizeof(_curium_fmt_buf), "%p",  (void*)(v)),    _curium_fmt_buf)  \
)
static char _curium_fmt_buf[64];

/* Forward Declarations */

int curium_abs(int);
int curium_max(int, int);
int curium_min(int, int);
int curium_clamp(int, int, int);
double curium_abs_f64(double);
double curium_max_f64(double, double);
double curium_min_f64(double, double);
int curium_pow_int(int, int);
int curium_factorial(int);
void curium_main(void);


/* Closure Functions */
int curium_abs(const int curium_x)
{
    if ((curium_x < 0)) {
        return (0 - curium_x);
    }
    return curium_x;
}

int curium_max(const int curium_a, const int curium_b)
{
    if ((curium_a > curium_b)) {
        return curium_a;
    }
    return curium_b;
}

int curium_min(const int curium_a, const int curium_b)
{
    if ((curium_a < curium_b)) {
        return curium_a;
    }
    return curium_b;
}

int curium_clamp(const int curium_x, const int curium_lo, const int curium_hi)
{
    if ((curium_x < curium_lo)) {
        return curium_lo;
    }
    if ((curium_x > curium_hi)) {
        return curium_hi;
    }
    return curium_x;
}

double curium_abs_f64(const double curium_x)
{
    if ((curium_x < 0.0)) {
        return (0.0 - curium_x);
    }
    return curium_x;
}

double curium_max_f64(const double curium_a, const double curium_b)
{
    if ((curium_a > curium_b)) {
        return curium_a;
    }
    return curium_b;
}

double curium_min_f64(const double curium_a, const double curium_b)
{
    if ((curium_a < curium_b)) {
        return curium_a;
    }
    return curium_b;
}

int curium_pow_int(const int curium_base, const int curium_exp)
{
    int curium_result = 1;
    int curium_i = 0;
    while ((curium_i < curium_exp)) {
        curium_result = (curium_result * curium_base);
        curium_i = (curium_i + 1);
    }
    return curium_result;
}

int curium_factorial(const int curium_n)
{
    if ((curium_n <= 1)) {
        return 1;
    }
    return (curium_n * curium_factorial((curium_n - 1)));
}

/* unknown statement */
void curium_main()
{
    const int curium_a = 3;
    const int curium_b = 2;
    const int curium_c = curium_pow_int(curium_a, curium_b);
    curium_print(curium_string_format("C = %s", curium_any_to_str(curium_c)));
}


int main(int argc, char** argv) {
    (void)argc; (void)argv;
    curium_gc_init();
    curium_main();
    curium_gc_shutdown();
    return 0;
}
