/* Generated by Curium v5 compiler — do not edit */
#include "curium/core.h"
#include "curium/memory.h"
#include "curium/string.h"
#include "curium/list.h"
#include "curium/array.h"
#include "curium/map.h"
#include "curium/safe_ptr.h"
#include "curium/option.h"
#include "curium/result.h"
#include "curium/http.h"
#include "curium/thread.h"
#include "curium/file.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <setjmp.h>
#include <stdint.h>

/* Exception Handling Runtime */
#define CURIUM_MAX_EX_DEPTH 64
/* FIX #014: exception globals are _Thread_local so that spawn {} threads
 * have independent exception stacks — a throw on one thread no longer
 * corrupts another thread's setjmp/longjmp state.                      */
#if defined(__TINYC__)
#  define CURIUM_TLS  /* TCC: no TLS support */
#elif defined(_MSC_VER)
#  define CURIUM_TLS __declspec(thread)
#elif defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L
#  define CURIUM_TLS _Thread_local
#elif defined(__GNUC__) || defined(__clang__)
#  define CURIUM_TLS __thread
#else
#  define CURIUM_TLS  /* no TLS support — fallback to global */
#endif
CURIUM_TLS jmp_buf _curium_ex_stack[CURIUM_MAX_EX_DEPTH];
CURIUM_TLS int _curium_ex_depth = 0;
CURIUM_TLS void* _curium_current_exception = NULL;

#define CURIUM_THROW_IMPL(ex) do { \
    _curium_current_exception = (void*)(ex); \
    if (_curium_ex_depth > 0) longjmp(_curium_ex_stack[_curium_ex_depth - 1], 1); \
    else { fprintf(stderr, "Uncaught exception\n"); exit(1); } \
} while(0)

static inline void* curium_result_unwrap_or_throw(curium_result_t res) {
    if (res.kind == CURIUM_RESULT_ERR) CURIUM_THROW_IMPL(curium_string_new("Result Error"));
    return res.value;
}

#define CURIUM_RESULT_OK(val)  curium_result_ok( &(val),  sizeof(val) )
#define CURIUM_RESULT_ERR(err) curium_result_err(&(err),  sizeof(err) )
#define CURIUM_OPTION_SOME(val) curium_option_some(&(val), sizeof(val))
#define CURIUM_OPTION_NONE CURIUM_OPTION_NONE_INIT

/* Type Erasure for Generics (Fallback to void*) */
typedef void* T;
typedef void* U;
typedef void* K;
typedef void* V;

static char _curium_fmt_buf[64];

#ifndef __cplusplus
#define curium_any_to_str(v) _Generic((v),                                   \
    curium_string_t*: ((curium_string_t*)(v))->data,                          \
    char*:            (v),                                                    \
    const char*:      (v),                                                    \
    int:              (snprintf(_curium_fmt_buf, sizeof(_curium_fmt_buf), "%d", (int)(v)),      _curium_fmt_buf), \
    unsigned int:     (snprintf(_curium_fmt_buf, sizeof(_curium_fmt_buf), "%u", (unsigned int)(v)), _curium_fmt_buf), \
    long:             (snprintf(_curium_fmt_buf, sizeof(_curium_fmt_buf), "%ld", (long)(v)),    _curium_fmt_buf), \
    unsigned long:    (snprintf(_curium_fmt_buf, sizeof(_curium_fmt_buf), "%lu", (unsigned long)(v)), _curium_fmt_buf), \
    double:           (snprintf(_curium_fmt_buf, sizeof(_curium_fmt_buf), "%g",  (double)(v)),   _curium_fmt_buf), \
    float:            (snprintf(_curium_fmt_buf, sizeof(_curium_fmt_buf), "%g",  (double)(v)),   _curium_fmt_buf), \
    default:          (snprintf(_curium_fmt_buf, sizeof(_curium_fmt_buf), "%p",  (void*)(v)),    _curium_fmt_buf)  \
)
#else
static inline const char* curium_any_to_str(curium_string_t* s) { return s->data; }
static inline const char* curium_any_to_str(char* s) { return s; }
static inline const char* curium_any_to_str(const char* s) { return s; }
static inline const char* curium_any_to_str(int v) { snprintf(_curium_fmt_buf, 64, "%d", v); return _curium_fmt_buf; }
static inline const char* curium_any_to_str(unsigned int v) { snprintf(_curium_fmt_buf, 64, "%u", v); return _curium_fmt_buf; }
static inline const char* curium_any_to_str(long v) { snprintf(_curium_fmt_buf, 64, "%ld", v); return _curium_fmt_buf; }
static inline const char* curium_any_to_str(unsigned long v) { snprintf(_curium_fmt_buf, 64, "%lu", v); return _curium_fmt_buf; }
static inline const char* curium_any_to_str(float v) { snprintf(_curium_fmt_buf, 64, "%g", (double)v); return _curium_fmt_buf; }
static inline const char* curium_any_to_str(double v) { snprintf(_curium_fmt_buf, 64, "%g", v); return _curium_fmt_buf; }
static inline const char* curium_any_to_str(void* v) { snprintf(_curium_fmt_buf, 64, "%p", v); return _curium_fmt_buf; }
#endif


    #include <iostream>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward Declarations */

void curium_main(void);


/* Closure Functions */
void curium_main()
{
    
        for(int i=0; i<1000; i++) {
            std::cout << "STDOUT DATA LINE " << i << " BLAH BLAH BLAH BLAH BLAH" << std::endl;
            std::cerr << "STDERR DATA LINE " << i << " BLAH BLAH BLAH BLAH BLAH" << std::endl;
        }
    
}


int main(int argc, char** argv) {
    (void)argc; (void)argv;
    curium_gc_init();
    curium_main();
    curium_gc_shutdown();
    return 0;
}

#ifdef __cplusplus
}
#endif
