"""
Export YouTube cookies from your browser to cookies.txt for yt-dlp.
Usage: python export_cookies.py [chrome|firefox|edge]
Requirements: pip install browser-cookie3
"""
import sys
import time

def export_cookies(browser='firefox'):
    try:
        import browser_cookie3
    except ImportError:
        print("Installing browser-cookie3...")
        import subprocess
        subprocess.check_call([sys.executable, "-m", "pip", "install", "browser-cookie3"])
        import browser_cookie3

    print(f"Exporting cookies from {browser}...")
    print("NOTE: Close your browser first, then run this script!\n")

    try:
        if browser == 'chrome':
            cj = browser_cookie3.chrome(domain_name='.youtube.com')
        elif browser == 'firefox':
            cj = browser_cookie3.firefox(domain_name='.youtube.com')
        elif browser == 'edge':
            cj = browser_cookie3.edge(domain_name='.youtube.com')
        else:
            print(f"Unknown browser: {browser}. Use chrome, firefox, or edge.")
            return

        # Write Netscape format cookies.txt
        with open("cookies.txt", "w") as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# Generated by export_cookies.py\n\n")
            for cookie in cj:
                if 'youtube' in cookie.domain or 'google' in cookie.domain:
                    secure = "TRUE" if cookie.secure else "FALSE"
                    http_only = "TRUE" if cookie.has_nonstandard_attr('HttpOnly') else "FALSE"
                    expires = int(cookie.expires) if cookie.expires else int(time.time()) + 3600
                    domain = cookie.domain if cookie.domain.startswith('.') else '.' + cookie.domain
                    f.write(f"{domain}\tTRUE\t{cookie.path}\t{secure}\t{expires}\t{cookie.name}\t{cookie.value}\n")

        print("✅ cookies.txt exported successfully!")
        print("Copy cookies.txt to C:\\Users\\wWw\\Documents\\CM\\build\\")
        print("Then restart cm_server.exe and try downloading again.")

    except Exception as e:
        print(f"Error: {e}")
        print("\nManual alternative:")
        print("1. Install the 'Get cookies.txt LOCALLY' Chrome/Firefox extension")
        print("2. Go to youtube.com while logged in")
        print("3. Click the extension and export cookies.txt")
        print("4. Place cookies.txt in C:\\Users\\wWw\\Documents\\CM\\build\\")

if __name__ == "__main__":
    browser = sys.argv[1] if len(sys.argv) > 1 else 'firefox'
    export_cookies(browser)
