/* Generated by Curium v4 compiler — do not edit */
#include "curium/core.h"
#include "curium/memory.h"
#include "curium/string.h"
#include "curium/list.h"
#include "curium/array.h"
#include "curium/map.h"
#include "curium/safe_ptr.h"
#include "curium/option.h"
#include "curium/result.h"
#include "curium/http.h"
#include "curium/thread.h"
#include "curium/file.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <setjmp.h>
#include <stdint.h>

/* Exception Handling Runtime */
#define CURIUM_MAX_EX_DEPTH 64
jmp_buf _curium_ex_stack[CURIUM_MAX_EX_DEPTH];
int _curium_ex_depth = 0;
void* _curium_current_exception = NULL;

#define CURIUM_THROW_IMPL(ex) do { \
    _curium_current_exception = (void*)(ex); \
    if (_curium_ex_depth > 0) longjmp(_curium_ex_stack[_curium_ex_depth - 1], 1); \
    else { fprintf(stderr, "Uncaught exception\n"); exit(1); } \
} while(0)

static inline void* curium_result_unwrap_or_throw(curium_result_t res) {
    if (res.kind == CURIUM_RESULT_ERR) CURIUM_THROW_IMPL(curium_string_new("Result Error"));
    return res.value;
}

#define CURIUM_RESULT_OK(val) ({ __typeof__(val) _v = (val); curium_result_ok(&_v, sizeof(_v)); })
#define CURIUM_RESULT_ERR(err) ({ __typeof__(err) _e = (err); curium_result_err(&_e, sizeof(_e)); })
#define CURIUM_OPTION_SOME(val) ({ __typeof__(val) _v = (val); curium_option_some(&_v, sizeof(_v)); })
#define CURIUM_OPTION_NONE CURIUM_OPTION_NONE_INIT

/* Type Erasure for Generics (Fallback to void*) */
typedef void* T;
typedef void* U;
typedef void* K;
typedef void* V;

/* Forward Declarations */

void curium_main(void);


/* Closure Functions */
void curium_main()
{
    curium_println(curium_string_new("Hello, fixture!"));
}


int main(int argc, char** argv) {
    (void)argc; (void)argv;
    curium_gc_init();
    curium_main();
    curium_gc_shutdown();
    return 0;
}
